export const defaultStyles = {
  heading: {
    color: "#1f2937",
    fontSize: "32px",
    fontWeight: "700",
    backgroundColor: "transparent",
    padding: "8px",
    margin: "0px",
    borderRadius: "8px",
    borderWidth: "0px",
    borderColor: "#e5e7eb",
    textAlign: "left",
    opacity: 1,
    transform: "scale(1)",
    transition: "all 0.3s ease",
    boxShadow: "none",
  },
  paragraph: {
    color: "#6b7280",
    fontSize: "16px",
    fontWeight: "400",
    backgroundColor: "transparent",
    padding: "8px",
    margin: "0px",
    borderRadius: "8px",
    borderWidth: "0px",
    borderColor: "#e5e7eb",
    textAlign: "left",
    opacity: 1,
    transform: "scale(1)",
    transition: "all 0.3s ease",
    boxShadow: "none",
  },
  button: {
    color: "#ffffff",
    fontSize: "14px",
    fontWeight: "500",
    backgroundColor: "#be123c",
    padding: "12px 24px",
    margin: "0px",
    borderRadius: "8px",
    borderWidth: "0px",
    borderColor: "#be123c",
    textAlign: "center",
    opacity: 1,
    transform: "scale(1)",
    transition: "all 0.3s ease",
    boxShadow: "0 4px 6px -1px rgba(0, 0, 0, 0.1)",
  },
  input: {
    color: "#374151",
    fontSize: "14px",
    fontWeight: "400",
    backgroundColor: "#f9fafb",
    padding: "12px 16px",
    margin: "0px",
    borderRadius: "8px",
    borderWidth: "1px",
    borderColor: "#e5e7eb",
    textAlign: "left",
    opacity: 1,
    transform: "scale(1)",
    transition: "all 0.3s ease",
    boxShadow: "none",
  },
};

export const getElementDisplayName = (elementId) => {
  const names = {
    heading: "Heading",
    paragraph: "Paragraph",
    button: "Button",
    input: "Input",
  };
  return names[elementId] || "Element";
};
